---

name: WRN-50-2

gops: [22.818]

shapes:
  - [1, 3, 224, 224]

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/WRN-50-2.onnx
    --test_input $(root)/dataset/samples/cat.jpg
    --input_shapes [$(shape_param)]
    --mean 123.675,116.28,103.53
    --scale 0.01712475,0.01750700,0.01742919
    --pixel_format rgb
    --output_names 495
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/transformed.mlir

mlir_calibration:
  run_calibration.py $(workdir)/transformed.mlir
    --dataset $(imagenet2012_cali_set)
    --input_num 100
    -o $(workdir)/$(name).cali_table

BM1684X:
  deploy:
    - model_deploy.py  --mlir $(workdir)/transformed.mlir
        --quantize F32
        --chip bm1684x
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.99,0.99
        --model $(workdir)/$(name)_bm1684x_f32.bmodel
    - model_deploy.py --mlir $(workdir)/transformed.mlir
        --quantize INT8
        --calibration_table $(workdir)/$(name).cali_table
        --quant_input
        --quant_output
        --chip bm1684x
        --test_input $(workdir)/$(name)_in_f32.npz
        --test_reference $(name)_top_outputs.npz
        --tolerance 0.85,0.45
        --model $(workdir)/$(name)_bm1684x_int8_sym.bmodel
    - model_deploy.py --mlir $(workdir)/transformed.mlir
      --quantize INT8
      --asymmetric
      --calibration_table $(workdir)/$(name).cali_table
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.90,0.55
      --model $(workdir)/$(name)_bm1684x_int8_asym.bmodel

  dataset:
    image_path: $(imagenet2012_val_set)
    image_label: $(imagenet2012_caffe_val_ground_truth)
    mean: [123.675, 116.28, 103.53]
    scale: [0.01712475, 0.01750700, 0.01742919]
    resize_dims: 256
    size: 224
    trans: True
    bgr2rgb: True

  harness:
    type: topk
    args:
      - name: FP32
        bmodel: $(workdir)/$(name)_bm1684x_f32.bmodel
      - name: INT8
        bmodel: $(workdir)/$(name)_bm1684x_int8_sym.bmodel
      - name: AINT8
        bmodel: $(workdir)/$(name)_bm1684x_int8_asym.bmodel
