---

name: tpu-mlir_S-DCNet_SHB

gops: [120.37]

shapes:
  - [1, 3, 384, 512]

mlir_transform:
  model_transform.py
    --model_name $(name)
    --model_def $(home)/S-DCNet_SHB.onnx
    --test_input $(root)/dataset/samples/cat.jpg
    --input_shapes [$(shape_param)]
    --mean 116.5337658,114.2056311,110.29177125
    --scale 0.0039216,0.0039216,0.0039216
    --pixel_format rgb
    --output_names 63,70,77,84
    --test_result $(name)_top_outputs.npz
    --mlir $(workdir)/S-DCNet_SHB_transformed.mlir

mlir_calibration:
  run_calibration.py $(workdir)/S-DCNet_SHB_transformed.mlir
    --dataset $(coco2017_mlir_cali_set)
    --input_num 100
    -o $(home)/S-DCNet_SHB_cali_table

deploy:
  - model_deploy.py  --mlir $(workdir)/S-DCNet_SHB_transformed.mlir
      --quantize F32
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.99,0.99
      --model $(workdir)/$(name)_bm1684x_f32.bmodel
  - model_deploy.py --mlir $(workdir)/S-DCNet_SHB_transformed.mlir
      --quantize INT8
      --calibration_table $(home)/S-DCNet_SHB_cali_table
      --quant_input
      --quant_output
      --chip bm1684x
      --test_input $(workdir)/$(name)_in_f32.npz
      --test_reference $(name)_top_outputs.npz
      --tolerance 0.85,0.45
      --model $(workdir)/$(name)_bm1684x_int8_sym.bmodel
  - model_deploy.py --mlir $(workdir)/S-DCNet_SHB_transformed.mlir
    --quantize INT8
    --asymmetric
    --calibration_table $(home)/S-DCNet_SHB_cali_table
    --chip bm1684x
    --test_input $(workdir)/$(name)_in_f32.npz
    --test_reference $(name)_top_outputs.npz
    --tolerance 0.90,0.55
    --model $(workdir)/$(name)_bm1684x_int8_asym.bmodel